### PR TITLE
Introduce the //unsummon command

### PR DESCRIPTION
**Pull request by TheOneWhoMade**
Unsummon command start. Note: This is a start and is not expected to function completely.

## What does this PR do?
This is a start for the Unsummon command. This enables a bot to 'leave' a room. In reality it simply ignores replies and commands from a room.

### CODE REVIEW

**Comment by TheOneWhoMade** [comment]
Solves part of #8

**Comment by LunarWatcher** [comment]
Rejected

Already created

**Comment by TheOneWhoMade** [comment]
Close your issue then.

**Comment by TheOneWhoMade** [comment]
@LunarWatcher  did you actually look at my first commit?

**Comment by TheOneWhoMade** [comment]
@LunarWatcher I might as well ask you. Would you mind if I made a port of your bot to JS? https://github.com/TheOneWhoMade/Node-NN-chatbot

**Comment by TheOneWhoMade** [comment]
You going to answer me?

**Comment by TheOneWhoMade** [comment]
**I'll take this as a yes.**

**Pull request closed without merging**
