### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by TheOneWhoMade**
You forgot one dependency.

### CODE REVIEW

**Comment by TheOneWhoMade** [comment]
```
Traceback (most recent call last):
  File "bot.py", line 3, in <module>
    import tensorlayer as tl
  File "/usr/local/lib/python3.4/dist-packages/tensorlayer/__init__.py", line 12, in <module>
    from . import files
  File "/usr/local/lib/python3.4/dist-packages/tensorlayer/files.py", line 49, in <module>
    from . import nlp, utils, visualize
  File "/usr/local/lib/python3.4/dist-packages/tensorlayer/visualize.py", line 6, in <module>
    import scipy.misc  # save/read image(s)
ImportError: No module named 'scipy'

```

**Comment by LunarWatcher** [comment]
Scipy is a dependency from tensorlayer. It most likely doesn't get installed without pip. It's an indirect dependency, there isn't really a need to specify it

**Comment by TheOneWhoMade** [comment]
Well, it's preventing the bot from being run.

**Comment by LunarWatcher** [comment]
I'm going to close this PR. Scipy is a dependency of tensorlayer, not the chatbot itself. Installing the other dependencies also includes installing their dependencies. If all the dependencies' dependencies were to be listed, it'd be a really long list.

**Pull request closed without merging**
