### PR TITLE
Update Commands.py

### PR DESCRIPTION
**Pull request by TheOneWhoMade**
Applied the same optimization as the one used in #16

# What does this PR do?
Optimization.

### CODE REVIEW

**Comment by TheOneWhoMade** [comment]
Smaller space + better performance! 😄

**Comment by TheOneWhoMade** [comment]
I'm assuming your tired of the optimizations.

**Comment by LunarWatcher** [comment]
I'm assuming you didn't read my comment on the minimization issue. I'm gonna be creating contribution guidelines eventually btw, if you're gonna pull make sure it's a substantial change. Pulling single-line edits multiple times a day isn't something I want to spend time on

**Comment by TheOneWhoMade** [comment]
So you want me to make several changes and then pull?

**Pull request closed without merging**
