### PR TITLE
Update bot.py

### LINKED ISSUE #23: Optimize boot
*Only applies to chatting*

Launch the bot and net async, so the bot can get online quickly independently of the network.

### PR DESCRIPTION
**Pull request by TheOneWhoMade**
Made some of it async.

# What does this PR do?
Closes #23

### CODE REVIEW

**Comment by LunarWatcher** [comment]
Rejected

This is not closing it..

**Comment by LunarWatcher** [comment]
#23 is supposed to separate bot and net loading to deal with the net loading time

**Comment by TheOneWhoMade** [comment]
By net you mean Nueral Net?

**Comment by LunarWatcher** [comment]
Yes. Loading chatting and the net separate allows for faster boot. And chatexchange is forced async by the code creating its instance

**Comment by TheOneWhoMade** [comment]
What I am thinking is you could load the bot chatting, wait 5 seconds, and add all methods using techniques mentioned in this SO answer: https://stackoverflow.com/questions/972/adding-a-method-to-an-existing-object-instance

**Comment by TheOneWhoMade** [comment]
```
class Foo(object):
    '''An empty class to demonstrate adding a method to an instance'''
#Create an instance:

foo = Foo()
#Create a method to add to it:

def sample_method(self, bar, baz):
    print(bar + baz)
````

**Comment by TheOneWhoMade** [comment]
Which would you like to load first? The

**Pull request closed without merging**
